sonar.projectKey=jon-lipsky-sonarsource_clipper2-java
sonar.organization=jon-lipsky-sonarsource
sonar.host.url=https://sonarcloud.io
sonar.coverage.jacoco.xmlReportPaths=build/reports/jacoco/test/jacocoTestReport.xml
sonar.gradle.skipCompile=true
